name: dcql
description: A Dart implementation of Digital Credentials Query Language (DCQL) for querying credentials from digital wallets.
version: 0.0.1

environment:
  sdk: ^3.6.0

dev_dependencies:
  melos: ^6.3.2
  lints: ^5.1.1
  test: ^1.24.0
  build_runner: ^2.4.0
  coverage: ^1.11.1
