name: dcql
description: A Dart implementation of Digital Credentials Query Language (DCQL) for querying credentials from digital wallets.
version: 0.0.1

environment:
  sdk: ^3.6.0

dev_dependencies:
  melos: ^6.3.2
